overrides:
  ceph_ansible:
    rhbuild: '2.2'
    vars:
      ceph_conf_overrides:
          global:
            osd_default_pool_size: 2
            osd_pool_default_pg_num: 128
            osd_pool_default_pgp_num: 128
      ceph_stable_release: luminous
      ceph_origin: distro
      ceph_stable: true
      ceph_stable_rh_storage: true
      ceph_test: true
      journal_size: 1024
      osd_auto_discovery: false
      osd_scenario: collocated
tasks:
- ssh-keys:
- ceph-ansible:
- systemd:
- workunit:
    clients:
      all:
      - rados/load-gen-mix.sh
