tasks:
- ssh-keys: null
- ceph-ansible: null
- rgw-system-test:
    test: test_version_with_revert
    test_version: v1
    clients: ['client.0']
    config:
       user_count: 2
       bucket_count: 25
       objects_count: 10
       version_count: 5
       min_file_size: 50
       max_file_size: 60