overrides:
  ceph:
    log-whitelist:
      - but it is still running
      - 'noup flag(s) set'
      - OSDMAP_FLAGS
      - OSD_OUT_OF_ORDER_FULL
      - CACHE_POOL_NO_HIT_SET  
    conf:
      client:
        rbd cache: true
      global:
        ms inject socket failures: 5000
tasks:
- install: null
- ceph:
    fs: xfs
- thrashosds:
    timeout: 1200
- rbd_fsx:
    clients:
    - client.0
    ops: 2000
