tasks:
- ssh-keys: null
- ceph-ansible:
    vars:
      cluster: c1
- ceph-ansible:
    vars:
      cluster: c2
- new-rgw-multisite:
   realm:
     name: test-realm
     is_default: true
   zonegroups:
     - name: test-zg
       is_master: true
       is_default: true
       zones:
         - name: test-zone
           is_master: true
           is_default: true
           endpoints: [c1.rgw.0]
         - name: test-zone2
           is_default: true
           endpoints: [c2.rgw.1]
- multisite-test.userexec:
      master_client: c1.rgw.0
      test_dir_version: v1
      master_config:
        cluster_name: c1
        user_count: 3
      target_client: c2.rgw.1
- sleep:
      duration: 60
- multisite-test:
      test-name: test_acls_reset
      test_dir_version: v1
      master_client: c1.rgw.0
      target_client: c2.rgw.1
      target_config:
          bucket_count: 5
          objects_count: 10
          min_file_size: 10
          max_file_size: 20
- sleep:
      duration: 60
- multisite-test.pull-io-info:
