---
name: "Pull Request Triage"
on: pull_request_target
jobs:
  pr-triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@main
        with:
          sync-labels: ''
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: iyu/actions-milestone@v1
        with:
          configuration-path: .github/milestone.yml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
